name: vtki-environment
channels:
  - bokeh/label/dev
  - pyviz
dependencies:
  - python
  - bokeh
  - pyviz_comms
  - panel
  - pip:
    - git+git://github.com/sgkang/vtki
    - matplotlib
    - pyct
